CREATE TABLE IF NOT EXISTS `TB_USERS` (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    cpf_cnpj VARCHAR(14) UNIQUE NOT NULL,
    type ENUM('FISICA', 'JURIDICA') NOT NULL
);